
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/reservation?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: 11111111


    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
        show-sql: true
    properties:
        hibernate.format_sql: true
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect


logging:
    level:
        org.hibernate.SQL: debug


jwt:
    secret: hello.world.qwerasdf